version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/github_events
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  ui:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./ui:/usr/share/nginx/html
    depends_on:
      - web
volumes:
  mongodb_data: